### ISSUE TITLE
Some way to restrict or suggest phone numbers for a user?

### ISSUE THREAD

**Issue by da3dsoul** [duosecurity/duo_universal_csharp#18]
We have employee phones, which we control the phone numbers for, of course. As a security measure, we want to add MFA, with the primary method being registration via these phones. We want to allow registration using only the phone numbers we provide, read from our database, which our web application can look up.
In the login flow, there's a simple login form like in the example, it then goes to Duo, but I see no way of passing anything but the username (company email in this case) to suggest the login/registration methods.
Any suggestions how we should handle this?

**Comment by AaronAtDuo** [comment]
@da3dsoul Unfortunately this is not something Duo can currently support.  The closest thing I can think of would be to disallow self-service registration, and assign phones to users via the Admin Panel; but that might be too limiting.

Otherwise, I'd suggest contacting Duo's support organization to have them submit a feature request to support this use case.

**Comment by da3dsoul** [comment]
I think that's the direction we are going to go. Thanks for the reply. The mass import of users will make a database sync easy enough
