### ISSUE TITLE
strong naming the component

### ISSUE THREAD

**Issue by mwan1** [duosecurity/duo_universal_csharp#21]
is it a possibility to strong name the component and push to the nuget server?

**Comment by mwan1** [comment]
Looks like the package is signed - we see a .sha512 file downloaded.  
What we are looking for is either the dll being signed and/or the dll having a strong name.
e.g. 
![image](https://github.com/duosecurity/duo_universal_csharp/assets/6865308/ecdafdb9-e9df-4ae3-ac05-7bcac2985f24)
or
![image](https://github.com/duosecurity/duo_universal_csharp/assets/6865308/46c30176-164d-4959-9d67-fe7662e97c67)

**Comment by AaronAtDuo** [comment]
@mwan1 I will see what I can do, but the `dotnet pack` command does not support strong naming, as far as I can tell: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-pack

I will see if I can find a way to accomplish this.

**Comment by AaronAtDuo** [comment]
@mwan1 I have still been unable to find any way to add strong name signing to the dotnet packaging flow.  In order to maintain cross-platform compatibility I want to stick to their standard tooling, so I don't think we can accomplish this.

As far as I can tell, the general consensus is that end users who need strong named assemblies need to do that on their own, for example see some approaches in https://joshuachini.com/2017/07/12/how-to-assign-a-strong-name-to-unsigned-3rd-party-assemblies-during-the-build-process/.

Sorry we were unable to help with this, and thanks for using Duo.

**Comment by AaronAtDuo** [comment]
`dotnet pack` still does not support strong name signing, so we will be unable to do this.
